### ISSUE TITLE
Research And Creation Of Restful API

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#102]
Assignees will research and create Restful API.

_Deadline: 15.05.2020_

**Comment by FarukOzderim** [comment]
| **Data will be fetched by API team from google scholars** | _Gülperi, Enes, Hazer_ | _21.05.2020 23.59_ |

(https://github.com/fredrike/googlescholar-api)

**Comment by gulperii** [comment]
I suggest that we should change the third party api (GoogleScholarAPI) we have decided to work with. 
It offers very few functionalities. Instead I suggest two alternatives:
arXiv's official api : [https://arxiv.org/help/api/user-manual](https://arxiv.org/help/api/user-manual)
scholarly : [https://github.com/OrganicIrradiation/scholarly](https://github.com/OrganicIrradiation/scholarly)

**Comment by gulperii** [comment]
Simple python script that shows how to make basic queries using scholarly api is commited under practice-app

**Comment by isiktashamza** [comment]
scholar_util script that uses scholarly api is created and two endpoints for searching authors are created.

**Comment by FarukOzderim** [comment]
Thirdparty.py functionalities will be extended.
| **Extending Thirdparty API Functionalities** | _Gülperi,Enes,Hazer_ | _22.05.2020 23.59_ |

**Comment by hazerb** [comment]
Paper search functionality added to thirdparty.py
