### ISSUE TITLE
Coronavirus Endpoint

### ISSUE THREAD

**Issue by EnesToptas** [bounswe/bounswe2020group6#120]
Create a new endpoint in API for Coronavirus Data.
There is already one endpoint, please move it to another file and create more.

**Comment by Tubagc** [comment]
/countryLive endpoint added.
 /searchCountryLive route added.
 searchCountryName.html added.

**Comment by DogukanKalkan** [comment]
An endpoint for listing daily Covid19 statistics of a specific country is added.

**Comment by gulperii** [comment]
An endpoint for showing world statistics (total)  is added

**Comment by Tubagc** [comment]
I updated my endpoints according to new design. new news for the routes are:
/api/coronavirusCountryLive
/coronavirusCountryLive

**Comment by gulperii** [comment]
worldstats.html is added under /templates

**Comment by hazerb** [comment]
/coronavirus endpoint added
/api/coronavirus endpoint added
also, coronavirus.html added to /templates

**Comment by hazerb** [comment]
/api/coronavirus endpoint added
coronavirus.html is added under /templates

**Comment by DogukanKalkan** [comment]
4 endpoints have been created as requested.
