### ISSUE TITLE
Write and Perform Unit Tests 

### ISSUE THREAD

**Issue by EnesToptas** [bounswe/bounswe2020group6#124]
Write and perform Unit Tests on functionalities you created.

**Comment by salihozcelik** [comment]
I tested api_publicationsearch(). It works properly for now but might be a problem for the future, I found this api a little unreliable.

**Comment by Tubagc** [comment]
coronavirusCountryLive_test.py is added under unit_tests folder in coronavirus-dev branch.

**Comment by gulperii** [comment]
getWorldStats_test.py is added under unit_tests folder in coronavirus-dev branch.

**Comment by hazerb** [comment]
coronavirus_summary_test.py is added under unit_tests folder in coronavirus-dev branch.

**Comment by EnesToptas** [comment]
search() functions very well and api_authorstats() work as intended, but it's performance is worse than 2005 standards.

**Comment by DogukanKalkan** [comment]
A unit test for api.CoronavirusByCountry created in coronavirus_api_tests.py works properly.

**Comment by FarukOzderim** [comment]
Added isPlotDataFetchCorrect test under coronavirus_api_unit_test, and it works correctly.

**Comment by isiktashamza** [comment]
I added isGetAuthorCorrect function to scholar-unit-test and it works correctly.

**Comment by UkcaGreen** [comment]
I have performed unit tests of coinrank and authorpublications.
