### ISSUE TITLE
I couldn't deploy the code!

### ISSUE THREAD

**Issue by salihozcelik** [bounswe/bounswe2020group6#128]
I had an issue with amazon web service and docker. I need help!

**Comment by salihozcelik** [comment]
I and Hamza tried to deploy but had lots of mistakes.****
![WhatsApp Image 2020-05-26 at 13 54 31](https://user-images.githubusercontent.com/50530781/82893497-c721ac80-9f59-11ea-800a-55f467effe09.jpeg)
![WhatsApp Image 2020-05-26 at 13 53 53](https://user-images.githubusercontent.com/50530781/82893504-c8eb7000-9f59-11ea-8e50-bc1603f7a3a4.jpeg)
![WhatsApp Image 2020-05-26 at 13 54 47](https://user-images.githubusercontent.com/50530781/82893512-cab53380-9f59-11ea-98fb-def733e7cca3.jpeg)

**Comment by FarukOzderim** [comment]
This was solved by team.
