### ISSUE TITLE
Check If backend methods are working

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#136]
- [x] search()  @EnesToptas 

- [x] api_search()  @hazerb 

- [x] profile(name) @cemreefe 

- [x] api_authorpublications()  @UkcaGreen 

- [x] api_publicationsearch() @isiktashamza  @EnesToptas 

- [x] api_authorstats() @UkcaGreen @EnesToptas 

- [x] coronavirus() @hazerb 

- [x] api_coronavirus() @hazerb 

- [x] api_world_stats()  @gulperii 

- [x]  world_stats() @gulperii 

- [x] coronavirusByCountry() @DogukanKalkan 

- [x] api_coronavirusByCountry() @DogukanKalkan 

- [x] coronavirusCountryLive() @Tubagc 

- [x] api_coronavirusCountryLive() @Tubagc

**Comment by hazerb** [comment]
api_search() , coronavirus(), api_coronavirus() methods are working

**Comment by gulperii** [comment]
api_world_stats() and world_stats() are working properly

**Comment by Tubagc** [comment]
I tested api_coronavirusCountryLive() with postman.It works properly. It is currently in coronavirus-dev package. 
coronavirusCountryLive() works properly.

**Comment by EnesToptas** [comment]
Please also write unite tests for functions you have checked.

**Comment by salihozcelik** [comment]
I tested api_publicationsearch(). It works properly for now but might be a problem for the future, I found this api a little unreliable.

**Comment by DogukanKalkan** [comment]
The function api_coronavirusByCountry() has been tested with both POST and GET requests in Postman. It responds properly in both cases.

**Comment by gulperii** [comment]
Unit test for coronavirus_api.getWorldStats() is performed and it works properly

**Comment by UkcaGreen** [comment]
api_authorpublications() is working properly.

**Comment by EnesToptas** [comment]
search() functions very well and api_authorstats() work as intended, but it's performance is worse than 2005 standards. unit tests are also written.

**Comment by DogukanKalkan** [comment]
A unit test for the function coronavirusByCountry() has been created and performed. It works properly.

**Comment by cemreefe** [comment]
### I tested the `profile(name)` method. 

- First things first, it works on my local, after several hours of inactivity for like 3 or 5 times. After that number of requests, the IP is temporarily banned from *Google Scholars* so the endpoint stops serving data. 

- As for the server, it looks as though the server's IP is permanently banned from reaching *Google Scholars*' endpoints. 

### What makes you think this way?
- I haven't been able to get any successful returns from any endpoint that makes use of Scholarly. Other endpoints seem to work fine.

### And the unit tests?
- I have written the unit test for this function and it also starts to fail after 3 to 5 successful runs (on local).
