### ISSUE TITLE
Create Milestone2 Deadline : 27.05.2020 23.55

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#148]
Milestone 2 Group Deriverable will be created.

Choose one or more and write. And comment. We can use Milestone 1 as a template.

● Executive Summary: Summary of project status and any changes that are planned for moving forward
○ Introduction
○ Work done so far
○ Road ahead
○ Challenges you met as a group
● List and status of deliverables.
● Evaluation of the status of deliverables and its impact on your project plan.
● A brief and clear summary of the work done by each team member (in tabular format).
○ Bad example
■ I attended lectures and group meetings. I also wrote some unit tests.
○ Good example
■ I implemented X method of Y API in Z file, and prepared the Q unit test to test the
implemented X method.
● Evaluation of tools and processes you have used to manage your team project.
● API documentation and URL.

**Comment by gulperii** [comment]
Please use this link to edit the milestone report:
https://docs.google.com/document/d/1SI_Hh9mmuZare69bYCabzuTa2A1TNQLKjn9tlnwY7vA/edit?usp=sharing

**Comment by FarukOzderim** [comment]
https://drive.google.com/open?id=1sjq6IJHHNFIWcqNQIda2Lzb2H9mT-t47

This link contains  milestone1, there are a lot of same parts that comes from Milestone1, pls combine these 2 milestone report links.

**Comment by UkcaGreen** [comment]
Evaluation of Tools section is added

**Comment by UkcaGreen** [comment]
Evaluation of Deliverables section is added

**Comment by UkcaGreen** [comment]
Summary of Work Done by Members section is added however it needs to be updated by groups members.

**Comment by UkcaGreen** [comment]
api/coinrankins and api/authorpublications documentations are added.

**Comment by Tubagc** [comment]
api/coronavirusCountryLive documentation is added. Summary of work done updated.

**Comment by EnesToptas** [comment]
Summar of work done is updated for my part.
GET api/publicationsearch is added.
GET api/authorstats is added.
Flask is added to Evaluation of Tools.

**Comment by gulperii** [comment]
Personal contribution, introduction, challenges are added. Documented 4 endpoints, ( couldnt continue due to some proxy issues :(     )

**Comment by FarukOzderim** [comment]
Add List and status of delivarables,
Add plans for moving forward.
Add updated project plan ss

**Comment by DogukanKalkan** [comment]
I have written the part 'Work done so far' and added my personal contribution to the section 'Summary of Work Done by Members'.

**Comment by hazerb** [comment]
Added my personal contribution to the section 'Summary of Work Done by Members'.
