### ISSUE TITLE
Creating Personal Wiki Pages (Newcomers)

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#160]
Wellcome on board. Please create a personal wiki page for yourself. You can check the already existing ones as examples.

**Comment by aliramazanmert** [comment]
Completed my part

**Comment by dogruomerfaruk** [comment]
Done

**Comment by cihatkapusuz** [comment]
I have done my part aswell. Don't forget to add yourself on sidebar of the wikipage and the main wiki page. I am closing this issue.
