### ISSUE TITLE
Revise and Update Requirements

### ISSUE THREAD

**Issue by DogukanKalkan** [bounswe/bounswe2020group6#162]
The following team members will review the requirements from the last semester and update it if necessary.

-  **Ali Ramazan Mert**

- **Cihat Kapusuz**

- **Hamza Işıktaş**

- **Hazer Babur**

After the necessary work is done, the assignees should inform the other team members about the changes done in the process.

_Deadline : 29/10/2020, 23.59_

**Comment by cihatkapusuz** [comment]
We arranged meeting with the assignees through zoom to work on the requirements. Necessary updates done according to the project description.

**Comment by isiktashamza** [comment]
With a meeting through zoom, we made the necessary modifications about requirements. Here are the changes:
