### ISSUE TITLE
Revise and Update User Scenarios and Mockups

### ISSUE THREAD

**Issue by DogukanKalkan** [bounswe/bounswe2020group6#163]
The following team members will revise and update the User Scenarios and Mockups according to the changes done in the requirements. 

- **Ömer Faruk Özdemir**

- **Ezgi Gülperi Er**

- **Cemre Efe Karataş**

The assignees may take initiative and update the scenarios and mockups or create new ones even if there are no changes in the requirements.

_Deadline: 02/11/2020, 23.59_

**Comment by gulperii** [comment]
User Scenario - 3 and related mockup are revised.
Changes are the following:
1 - "Following" functionality is removed therefore any step related to that functionality is removed from the scenario.
2 - Follower number in the mockup is removed
3 - Acceptance criteria is updated with additional requirements

**Comment by FarukOzderim** [comment]
User Scenario 2 and related mockup are checked.
There is nothing conflicting with the new requirement updates.

**Comment by cemreefe** [comment]
User scenario 1 and its mockup are updated with respect to the changes in the requirements.
* All events regarding *browsing the website in guest mode* are discarded, and their *signed in* counterparts are added.
* Old sign-up field requirements are dropped and new ones are added (-social security number, +research interests)
