### ISSUE TITLE
Revise and Update Diagrams

### ISSUE THREAD

**Issue by DogukanKalkan** [bounswe/bounswe2020group6#164]
The following team members will revise and update the diagrams if necessary.

- **Doğukan Kalkan**

- **Emilcan Arıcan**

- **Ömer Faruk Doğru**

_Deadline: 02/11/2020, 23.59_

**Comment by UkcaGreen** [comment]
1. _Be Private_ diagram is removed.
2. _Search and Follow_ diagram is removed.
3. _File Complaints_ diagram is removed.
4. _See Upcoming Events in Detail_ diagram is changed into _See Upcoming/Former Events in Detail_ diagram . 
5. _Reject Collaboration Invitation_ diagram changed into _Accept/Reject Collaboration Invitation_ diagram.
6. _Send Collaboration Invitation_ diagram is recreated. 
7. _Rate User_ diagram is created.
8. _Search and View Profile_ diagram is created.
9. _Add Tags to a Project_ diagram is created.
10. All diagrams are formatted to follow aligned and coherent display.

**Comment by UkcaGreen** [comment]
Some issues related to *Class Diagrams*:
1. Invitation and Requests are seems like same, if there is no difference one of them should be removed.
2. *getInvitations(int: user_id)* function is needed for *Registered_User*.
3. *getProjects(int: user_id)* function is needed for *Registered_User*.

**Comment by DogukanKalkan** [comment]
**Class Diagram is updated. The changes are the following:**

1. Guest user is removed.

2. Report functionality is removed.

3. _Affiliation_ class is added.

4. Follow functionality is removed.

5. Public/Private chocies for profile pages are removed.

6. Message functionality is removed.

7. Synchronization with a calender app is removed. 

**In addition to these changes which are consequences of the changes in requirements, there are a few more changes, which are listed below:**

1.  _Milestone_ class is created. 

2. _Paper_ class is created. 

3. _Request_ class is removed due to the duplication.

4. Two functions, _getInvitations_ and _getProjects_ are added to RegisteredUser class.

**Comment by dogruomerfaruk** [comment]
Use case diagram has updated with following changes:

-Guest user is removed and unregistered user is added.
-Reporting funtionality is removed.
-Following functionality case is removed.
-Profile visibility (public/private) is removed.
-Calendar sync removed.
-State whether users are currently seeking for new collaborations case is removed.
-Rate functionality cases are added.
