### ISSUE TITLE
Revise and Update Project Plan

### ISSUE THREAD

**Issue by DogukanKalkan** [bounswe/bounswe2020group6#165]
The following team members will update the project plan that will be executed throughout the semester.

- **Tuba Çibuk**

- **Muhammed Enes Toptaş**

_Deadline: 02/11/2020, 23.59_

**Comment by Tubagc** [comment]
New tasks of the project plan is created and divided into 11 weeks.

LOGIN PAGE
(1.1.1.1) Week 1
- Backend implementation of login with name, surname, unique email address and password
- Frontend implementation of login with name, surname, unique email address and password
- Mobile implementation of login with name, surname, unique email address and password 
(1.1.1.2) Week 6
- Backend implementation of e-mail validation 
- Frontend implementation of e-mail validation 
-Mobile implemention of e-mail validation 
(1.1.1.3) Week 1
- Backend implementation of tagging system regarding research interests 
- Frontend implementation of tagging system regarding research interests 
- Mobile implementation of tagging system regarding research interests 
(1.1.1.4) Week 3
- Backend implementation of entering affiliation
- Frontend implementation of entering affiliation
- Mobile implementation of entering affiliation
PROFILE PAGE
(1.1.20.1) Week 1
- Backend implementation of the part about the research area, recent publications and affiliation.
- Frontend implementation of the part about the research area, recent publications and affiliation.
-Mobile implementation of the part about the research area, recent publications and affiliation.
(1.1.20.2) Week 6
- Backend implementation of linking Google Scholar and ResearchGate accounts.
- Frontend implementation of linking Google Scholar and ResearchGate accounts.
- Mobile implementation of linking Google Scholar and ResearchGate accounts.
(1.1.20.4) Week 3
- Backend implementation of seeing, accepting and rejecting invitations
- Frontend implementation of seeing, accepting and rejecting invitations
- Mobile implementation of seeing, accepting and rejecting invitations
(1.1.16) Week 11
- Backend implementation of account delete
- Frontend implementation of account delete
- Mobile implementation of account delete
(1.1.15) Week 4
- Backend implementation of log out
- Frontend implementation of log out
- Mobile implementation of log out
(1.1.20.5) Week 11
- Backend implementation of ratings and comments
- Frontend implementation of ratings and comments
- Mobile implementation of ratings and comments
(1.1.20.3) Week 10
- Backend implementation of editing all information entered by the user
- Frontend implementation of editing all information entered by the user
- Mobile implementation of editing all information entered by the user
CREATING / EDITING PAGE
(1.1.21.1 -1.1.21.6) Week 2
- Backend implementation of entering information of the project being created
- Frontend implementation of entering information of the project being created
- Mobile implementation of entering information of the project being created
(1.1.21.7) Week 10
- Backend implementation of tracking information shared by other collaborating users
- Frontend implementation of tracking information shared by other collaborating users
- Mobile implementation of tracking information shared by other collaborating users
(1.1.21.8) Week 6
- Backend implementation of simultaneous document preparation
- Frontend implementation of simultaneous document preparation
- Mobile implementation of simultaneous document preparation
PAPER / PROJECT PAGE
(1.1.22.1 , 1.1.22.3, 1.1.22.5) Week 2
- Backend implementation of creating and editing paper/project
- Frontend implementation of creating and editing paper/project
- Mobile implementation of creating and editing paper/project
(1.1.22.2, 1.1.22.4) Week 4
- Backend implementation of seeing the status of paper/project
- Frontend implementation of seeing the status of paper/project
- Mobile implementation of seeing the status of paper/project
(1.122.6 , 1.1.22.7) Week 3
- Backend implementation of  inviting a user, accepting and rejecting requests
- Frontend implementation of  inviting a user, accepting and rejecting requests
- Mobile implementation of  inviting a user, accepting and rejecting requests
SEARCH PAGE
(1.1.23.1, 1.1.23.2) Week 2
- Backend implemention of search
- Frontend implemention of search
- Mobile implemention of search
(1.1.23.3) Week 7
- Backend impementation of filtering system
- Frontend impementation of filtering system
- Mobile impementation of filtering system

(1.1.23.4, 1.2.1.2) Week 10
- Backend implementation semantic search
- Frontend implementation semantic search
- Mobile implementation semantic search

EVENTS PAGE
(1.1.24.1 – 1.1.24.3) Week 7
- Backend Implementation of events page
- Frontend Implementation of events page
- Mobile Implementation of events page
(1.1.24.4) Week 8
- Backend implementation of seeing events detailed 
- Frontend implementation of seeing events detailed 
- Mobile implementation of seeing events detailed 
HOME PAGE Week 4
- Backend implementation of home page
- Frontend implementation of home page
- Mobile implementation of home page
NOTIFICATION SYSTEM Week 8
- Backend implementation of notification system
- Frontend implementation of notification system
- Mobile implementation of notification system
DEPLOYMENT Week 1
- Deployment of backend
- Initializing automated deployment
MILESTONE1 Week 5
- preparation of milestone document
MILESTONE2 Week 9
- preparation of milestone document

**Comment by Tubagc** [comment]
[Ram Chart](https://github.com/bounswe/bounswe2020group6/blob/master/Files/Templates/RAM_451.pdf) is added.

**Comment by Tubagc** [comment]
Other necessary files added
