### ISSUE TITLE
Theme and Color Palette

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#166]
We should select choose a color palette for our application. This will be a two step process.

1. Android and Front-end teams will decide on a few color palette choices.
2. Android and Front-end teams will present their choices to the whole group and the final decision will be made via a _poll_.

The discussions will be carried out on Slack.

**Comment by UkcaGreen** [comment]
[https://coolors.co/generate](url)

This site might be usefull while picking color palette. It creates reasonably harmonious color sets, and users can lock the colors that they like.

**Comment by UkcaGreen** [comment]
Web designs of the _landing page_, _profile page_ and _login part_ is made by frontend team by using Figma.

**Comment by cemreefe** [comment]
From the [poll](https://www.strawpoll.me/21219589) created by @Tubagc , we started designing a template with [the most preferred color scheme](https://coolors.co/1d1e18-6b8f71-aad2ba-d9fff5-b9f5d8) (although it appears to have changed to changes to the design are possible).

![color_scheme](https://user-images.githubusercontent.com/44120900/98531800-ef942d80-2291-11eb-9645-c09afab40360.png)

See the [figma project](https://www.figma.com/file/29VKHxMLe0oeqyPc5iCBAJ/akademise-profil?node-id=0%3A1) for the proposed design of the front-end team.

![Screenshot from 2020-11-05 20-10-53](https://user-images.githubusercontent.com/44120900/98528133-f3718100-228c-11eb-9b25-31c23f17db5c.png)
![Screenshot from 2020-11-05 20-08-53](https://user-images.githubusercontent.com/44120900/98528154-fa988f00-228c-11eb-9d45-7df03e16b502.png)

**Comment by cemreefe** [comment]
If there are no objections from the front-end team, I'll be closing this issue shortly.
