### ISSUE TITLE
Requirements Revision

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#167]
After the lab session, our customer has commented on our changes in the [project requirements](https://github.com/bounswe/bounswe2020group6/wiki/Requirements), and other requirements in general. Most were accepted, with a few exceptions.

- [x] **Requirement 1.1.21.8:** 
  The requirement currently says "Collaborators shall be able to prepare document or article for submission simultaneously.", which can be interpreted in a way similar to "google docs" or "overleaf" where you can edit the same text body simultaneously. However, we want it to indicate a system similar to _github_'s. Both parties should be able to change the contents of a publication, but not at the same time.
- [x] A requirement about **password reset** should be written.
- [x] The **ending collaboration period** functionality should come back.
- [x] The **following other users** functionality should come back.
- [x] The requirement about **abstracts being shown on the search results** should come back.

**Comment by isiktashamza** [comment]
I reviewed the changes going to be made and concluded that they are acceptable.

**Comment by cihatkapusuz** [comment]
#### Added requirements:
- **1.1.3** Users shall be able to reset their passwords through their associated email. 
- **1.1.11** User shall be able to disable join requests to end call for collaboration phase.
- **1.1.22** Users shall be able to follow other users on the platform.
- **1.1.23.6** Users shall be able to see their followers.
- **1.1.23.7** Users shall be able to see people who they follow.
- **1.2.6** System shall provide a text editor for publishing documents and articles.

#### Changed requirements:
 - **1.1.24.8** Collaborators shall be able to prepare document or article for submission on the platform.(was **1.1.21.8** previously)
 - **1.2.2.1** System shall provide a homepage for each user, showcasing recent and followed users' paper/project(s).

**Comment by aliramazanmert** [comment]
I reviewed the changes made on the requirements and they seem okay.

**Comment by hazerb** [comment]
reviewed the changes made and there seems no problem.
