### ISSUE TITLE
Android Dev - Login / Signup Pages 

### ISSUE THREAD

**Issue by gulperii** [bounswe/bounswe2020group6#170]
As the first step, we will create login and signup pages for our mobile application. In our second meeting ( 07.11.2020) we have defined subtasks and assigned them to individuals. 
Below you can find the work breakdown: 

- [x] Creating the project template: Tuba

- [x] Login page : Doğukan

Signup page 
- [x]  Personal info page ( name, contact details, bio etc.) : Cihat
- [x] Academic affiliation and related information  : Gülperi
- [x] Research interests tagging system  : Gülperi

Deadline : 10.11 23.59

**Comment by Tubagc** [comment]
Created an android app template and pushed into android-dev branch.

**Comment by cihatkapusuz** [comment]
Created template for sign up flow and necessary activities'/fragments' files

**Comment by gulperii** [comment]
Created personal information page and necessary xml files

**Comment by DogukanKalkan** [comment]
Login page is updated and validation page is created.

**Comment by Tubagc** [comment]
Research interests tagging system is added
