### ISSUE TITLE
Front-End Dev - First Commission

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#172]
After the commission described in #168, the front end team got together to share the work for this week's goals. We have decided to go with the following division:

@aliramazanmert 
- [x]  Landing Page 🌵
- [x]  Login Page / Window

@cemreefe 
- [x]  Sign-Up Page
- [x]  Front-end for tags (of research interests on sign up)

@dogruomerfaruk 
- [x]  Paper/project creation page
- [x]  Paper/project edit page

@UkcaGreen 
- [x]  Search bar component 
- [x]  A page to display search results

**Under discussion**:
- [x]  ~Research area and recent publications display components~ 
  Profile Page Draft

Discussions regarding these tasks will be carried out under this issue.

**Comment by aliramazanmert** [comment]
I completed the landing page and the login modal form, modularized the landing header for other developers to reuse it, developed a responsive sidebar and general responsive design.

**Comment by cemreefe** [comment]
My tasks were as follows:
- [x]  Sign-Up Page
- [x]  Front-end for tags (of research interests on sign up)

### Sign-Up Page:
I completed the first draft of a front-end for the sign-up page. I used @aliramazanmert 's Landing Header module.

![Screenshot from 2020-11-10 02-23-43](https://user-images.githubusercontent.com/44120900/98609210-d4f79e00-22fd-11eb-8c14-f1d745c251e6.png)

### Front-end for tags
As we are using [Ant-Design](https://ant.design/), I choose to go with their native `Select` form component that makes use of a tag style display sistem.

**Comment by cemreefe** [comment]
The front-end team ([Emilcan](../../../UkcaGreen), [Ali](../../../aliramazanmert), [Ömer Faruk](../../../dogruomerfaruk) and I) got together on using Zoom & Figma to finalize the designs for the remaining pages. Implementation will follow.

**Comment by cemreefe** [comment]
All planned pages' designs are completed. Both on [Figma](https://www.figma.com/file/29VKHxMLe0oeqyPc5iCBAJ/akademise-profil?node-id=0%3A1) and [React](https://github.com/bounswe/bounswe2020group6/tree/frontend)
