### ISSUE TITLE
Test Research for Frontend, Backend and Mobile

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#174]
Unit tests will be used in backend necassary research should be made. Unit testing and other testing alternatives should be searched also for frontend and mobile platforms. 

- [x] Backend Unit Test Research/Learning
- [x] Frontend Test Research
- [x] Mobile Test Research

**Comment by cihatkapusuz** [comment]
We have already talked the unit tests with the instructor and will take action according to his feedback.
