### ISSUE TITLE
Research about KVKK and W3C

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#175]
All members should learn about W3C standarts and KVKK. 

There is a wiki page of our former research on W3C Activity Streams: [W3C Activity Streams Research](https://github.com/bounswe/bounswe2020group6/wiki/W3C-Activity-Streams-Research) 

- [x] [Ali Ramazan Mert](https://github.com/bounswe/bounswe2020group6/wiki/Ali-Ramazan-Mert)
- [ ] [Cemre Efe Karakaş](https://github.com/bounswe/bounswe2020group6/wiki/Cemre-Efe-Karakaş) 
- [x] [Cihat Kapusuz](https://github.com/bounswe/bounswe2020group6/wiki/Cihat-Kapusuz) 
- [ ] [Doğukan Kalkan](https://github.com/bounswe/bounswe2020group6/wiki/Do%C4%9Fukan-Kalkan)  
- [x] [Emilcan Arıcan](https://github.com/bounswe/bounswe2020group6/wiki/Emilcan-Ar%C4%B1can)
- [ ] [Ezgi Gülperi Er](https://github.com/bounswe/bounswe2020group6/wiki/Ezgi-G%C3%BClperi-Er)  
- [ ] [Hamza Işıktaş](https://github.com/bounswe/bounswe2020group6/wiki/Hamza-I%C5%9EIKTA%C5%9E)
- [ ] [Hazer Babur](https://github.com/bounswe/bounswe2020group6/wiki/Hazer-Babur)   
- [x] [Muhammed Enes Toptaş](https://github.com/bounswe/bounswe2020group6/wiki/Muhammed-Enes-Topta%C5%9F)
- [ ] [Ömer Faruk Doğru](https://github.com/bounswe/bounswe2020group6/wiki/%C3%96mer-Faruk-Do%C4%9Fru)
- [x] [Ömer Faruk Özdemir](https://github.com/bounswe/bounswe2020group6/wiki/Ömer-Faruk-Özdemir)
- [ ] [Tuba Çibuk](https://github.com/bounswe/bounswe2020group6/wiki/G%C3%BCls%C3%BCm-Tuba-%C3%87ibuk)

**Comment by UkcaGreen** [comment]
I have made my research on KVKK and W3C activity streams.

**Comment by FarukOzderim** [comment]
I have also made my research.
Some resources on KVKK:
https://www.mevzuat.gov.tr/MevzuatMetin/1.5.6698.pdf
https://www.kvkk.gov.tr/

**Comment by cihatkapusuz** [comment]
Read the KVKK to understand restrictions and took a look at [W3C Activity Streams](https://github.com/bounswe/bounswe2020group6/wiki/W3C-Activity-Streams-Research) page of our previous research

**Comment by aliramazanmert** [comment]
I took a look at KVKK regulations and researched about W3C activity streams in a way of at least learning what they are all about.

**Comment by EnesToptas** [comment]
I read KVKK regulations and W3C activity streams and somewhat understood how they are related to our project.
