### ISSUE TITLE
Endpoint Match for Requests

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#176]
Spesifications about what kind of endpoints should be produced and what data should they pass will be discussed under this issue.

**Comment by cemreefe** [comment]
For the sign-up page:
An endpoint that accepts post requests and creates a user instance accordingly, with the following fields:
* e-mail
* password
* name, surname
* affiliation (!)
* personal information (!)
* research area interests, or the keys of the area instances, in a list

**Comment by aliramazanmert** [comment]
We need a login post request end point:
It takes 

- e-mail

- password

Authentication type should be chosen to be token or session wise and then the response type would be arranged accordingly.

**Comment by Tubagc** [comment]
required fields for profile and project pages are attached. [database_items.zip](https://github.com/bounswe/bounswe2020group6/files/5554904/database_items.zip)
