### ISSUE TITLE
Update Class Diagram

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#177]
Class diagram going to be updated by considering the backend and endpoints that will be created.

**Comment by Tubagc** [comment]
We mobile team members (@Tubagc  @gulperii , @DogukanKalkan , @cihatbaktir ) met and decided on new components of profile page and publications page. Created a documentation and shared with the group members.

**Comment by cihatkapusuz** [comment]
Updated class diagram will be on the Milestone 1 report and our wiki page shortly, so this issue does not need to be held open.
