### ISSUE TITLE
Deployment of the Project on AWS DEADLINE: 19/11/20 23.59

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#178]
If necessary, an AWS student account will be created. Then project will be deployed on AWS in a docker image.

**Comment by EnesToptas** [comment]
This shouldn't be only assigned to backend team. Whole project must be deployed.

**Comment by UkcaGreen** [comment]
Right, whole project should be deployed. I'm fixing the assignees part. Thanks for correction.

**Comment by isiktashamza** [comment]
@EnesToptas  and I deployed the backend to AWS.

**Comment by aliramazanmert** [comment]
Initial frontend with a docker container is deployed to [akademise-frontend](http://ec2-54-236-12-137.compute-1.amazonaws.com/)

**Comment by cemreefe** [comment]
### Both backend and frontend are deployed to their respective amazon instances.

* [backend](http://ec2-54-173-244-46.compute-1.amazonaws.com:3000/)
* [frontend](http://ec2-54-236-12-137.compute-1.amazonaws.com/)

P.S.: Future work might include continuous integration, which is hard with student accounts.
