### ISSUE TITLE
New Database tables

### ISSUE THREAD

**Issue by EnesToptas** [bounswe/bounswe2020group6#179]
Following tables should be designed and **implemented** in the database

- [x] Users table should have more fields (tags, university etc.)

- [x] Papers

- [x] Projects

more details of these table can be found on communication channels.

**Comment by FarukOzderim** [comment]
I will try to do a design.

**Comment by FarukOzderim** [comment]
A database design is completed with terms according to team's last update.

**Comment by EnesToptas** [comment]
This is not just a design issue but also requires real implementation. @FarukOzderim

**Comment by FarukOzderim** [comment]
Database design and table creation scripts have been created.
#180

**Comment by FarukOzderim** [comment]
Database ORM DB tables and models are created #189
