### ISSUE TITLE
Connecting Mobile to Backend with Retrofit.

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#198]
Deadline 22/11/2020 23.59

@DogukanKalkan 

- [x] signup 

    "email": "academise.help@gmail.com",
    "password": "Academise_1",
    "name": "Test",
    "surname": "User"

- [x] saving token to local

- [x] login (no token check)
{
    "email": "academise.help@gmail.com",
    "password": "Academise_1"
}

// {"message": "success", "accessToken": token}

@gulperii 

- [x] personal info  (affiliation, researchAreas)  (token check)

{
    "researchAreas": ["aa","bb"],
    "affiliation":{
        "university": "boun",
        "department": "xde",
        "degree": "despacito"
    }
}

@cihatkapusuz 

- [x] search(projects according to their titles)

{
    "query": "er"
    "type": "1"
}

@Tubagc 

- [x] projects (token check)

{
    "topic": "academise.help@gmail.com",
    "title": "Academise_1"
    "tags": "bla bla"
    "abstract" :"njk"
    "isPublic": "true"
    "content": "aa"
    "status": "aa"
    "collaborators" : "aa"
    "deadline": "7127"
    "creation_date": "738"
    
}
- [x] validate(after signUp)

{
    "code": "942411"
}
// {"message": "Validation is successful"}

**Comment by hazerb** [comment]
at backend, structure for project creation is like this : 

title (str)
abstract (str)
privacy (int 0 ya da 1)
status (int 0 ya da 1)
deadline (date)
requirements (string)
collaborators (array of ids)
tags (array of str)

alongside of these datas you should send files too.

**Comment by gulperii** [comment]
All tasks are successfully done, issue is closed
