### ISSUE TITLE
Backend corrections that should be made

### ISSUE THREAD

**Issue by isiktashamza** [bounswe/bounswe2020group6#203]
- [x] validate controller may be merged into another controller

- [x] when adding collaborators to a project, check if the given ids belong to real users.

- [x] user can update other people's project. it needs fixing.

- [x] When updating and creating projects or profiles, check if given fields exist in the table. 

- [x] user can delete other people's projects. fix it.

- [x] send all project related things when sending profile.

- [x] return userid in login, too

- [x] add validation check to auth middleware

**Comment by isiktashamza** [comment]
Please do required changes in new branches and create pull requests. done indication should be marked after merging to backend branch

**Comment by hazerb** [comment]
second,third and fifth ones are done

**Comment by EnesToptas** [comment]
6th is done, 4th is not necessary.
