### ISSUE TITLE
Validation Email should be prettified

### ISSUE THREAD

**Issue by EnesToptas** [bounswe/bounswe2020group6#209]
A nice email template, coherent with colour palette of frontend should be created and be integrated with backend.

**Comment by cemreefe** [comment]
You can check this one out
[email.html](https://github.com/bounswe/bounswe2020group6/files/5610723/email.txt)

**Comment by cemreefe** [comment]
up

**Comment by EnesToptas** [comment]
not the most significant issue, can be done after resolving real problems.

**Comment by EnesToptas** [comment]
I have implemented this and pushed it to backend branch.
