### ISSUE TITLE
Design follow related pages for frontend

### ISSUE THREAD

**Issue by isiktashamza** [bounswe/bounswe2020group6#220]

**Comment by cemreefe** [comment]
What would be the follow related pages?
I am thinking of :
1. view followers
2. view following

I have seen no requirement on the requirements for being able to view **other users'** followers or followings. So I am assuming this page can be only viewed by the user. I would be happy if someone could confirm this.

**Comment by isiktashamza** [comment]
Actually I wrote it wrong. it should be follow related functionality.

**Comment by cemreefe** [comment]
Merged branch with related features #240
