### ISSUE TITLE
Frontend Weekly Tasks

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#228]
The following tasks are planned to be finished in the following week by the frontend team. 🚩
- [x] **All Notification Dropdown List** (@UkcaGreen)
- [x] **Invite button** (@aliramazanmert )
- [x] **Follow button** (@aliramazanmert )
- [x] **Followers / Following list** (@cemreefe )
- [x] **Display project status / deadline status in project details page** (@UkcaGreen)
- [x] **Text Edit Page** (@cemreefe )
- [x] **Parse google scholar** (Assign yourself)
- [x] **Preparing json templates for the home page, and other implemented components** (Assign yourself)

**Comment by aliramazanmert** [comment]
@cemreefe 
followers/ following listing part should be a modal opening from the profile page instead of a seperate page i think. I changed the definition of that task

**Comment by aliramazanmert** [comment]
I added invite and follow buttons to the profile page, when backend is ready we can connect them. Also invite button could be used in the project detail page as well maybe.

**Comment by UkcaGreen** [comment]
All notification dropdown list is created, however it is implemented as a modal instead of dropdown.

**Comment by UkcaGreen** [comment]
Necessary changes are made in order to display project status. Status is displayed via tag and deadline bullets are updated.
