### ISSUE TITLE
Android Dev - Weekly Task Breakdown

### ISSUE THREAD

**Issue by gulperii** [bounswe/bounswe2020group6#230]
@cihatkapusuz  @DogukanKalkan 
- [x] Prettifying mobile design + integrating new layout to existing pages : Cihat, Doğukan
- [ ] Pdf uploading option in project creation page 

@Tubagc 
- [ ] Creating file upload / delete / access functionalities and related pages : Tuba

@gulperii 

- [x] Logout

- [x] Project details page (another user's PoV)

- [x] Checking backend integration for project creation

**Comment by gulperii** [comment]
Logout is added, Project details page (from non-owner perspective) added but need to discuss user-id issue with the team

**Comment by Tubagc** [comment]
- I tried to handle file-related tasks but the assignee is changed. 
- I corrected the get and post endpoints of personal info and profile pages. Added new classes to access backend fields.
- In personal info page, I get the title, department, and university lists from the database.

**Comment by gulperii** [comment]
> Logout is added, Project details page (from non-owner perspective) added but need to discuss user-id issue with the team

- User-id issue is handles, only owner of the project can edit the details.
- Modified the project details pages according to new design

**Comment by cihatkapusuz** [comment]
Mobile design prettified and some changes done on project creation. Adding a file removed from plan of the 2nd milestone
