### ISSUE TITLE
Invitation and Notification Related Backend Connections

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#254]
Backend connection of the invitation button, invitations and notifications will be made.

Invitation button should be added to the system, two alternatives are:
- An invite button will be added into profile page (there should be a modal that lists projects).
- An invite button will be added into project details page (there should be a modal that lists users).

> Implementation of any of those approaches are welcome, but implementation of the both of those at the same time is preferred.

**Comment by aliramazanmert** [comment]
Working on this issue on the branch "frontend-invites"

**Comment by aliramazanmert** [comment]
Impelemented those two features in the  [#298](https://github.com/bounswe/bounswe2020group6/pull/298)

**Comment by aliramazanmert** [comment]
Closing the issue
