### ISSUE TITLE
Search Bug

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#257]
**Bug Description:**
When user searches without selecting any filter types, some user profiles are listed even if they do not match with the query.

**Where does it occur:**
Bug is observed in the search results page. However search bar is present at every logged in page. Therefore user might face this bug from almost any logged in page.

**Example Scenario:**
User opens the home page, and searched "ali", in that case user results like "jhon snow" are displayed as well. After user selects a filter type (user, project, all), bug no longer continues.

**Comment by cemreefe** [comment]
I have fixed this bug.

You can see the [related pull request](https://github.com/bounswe/bounswe2020group6/pull/270).

I will close this issue after the branch is merged.

**Comment by cemreefe** [comment]
Turns out the bug was not completely fixed. See pr #332 for the rest of the fix.
