### ISSUE TITLE
Endpoint Connection of the Follow Functionality

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#263]
Backend enpoints for the follow and unfollow functionalities are ready. 

Therefore endpoint connections for these functionalities should be made:
- Follow functionaliy
- Unfollow functionaliy

**Comment by aliramazanmert** [comment]
I'm working on this issue

**Comment by aliramazanmert** [comment]
This issue is done and merged into frontend. It is already in production, so closing this issue.
