### ISSUE TITLE
Profile Page Enhancement (Google Scholar Connection)

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#265]
The google scholar related data (citations, h index and i10 index, ...) should be displayed at the profile page.
And the related endpoint connections should be made.

**Comment by EnesToptas** [comment]
Calculating h or i10 index is not possible as it seems with the current API, so the data will be limited to "citations per year", and most popular up-to-20 publications of the user. @UkcaGreen beware of that.

**Comment by aliramazanmert** [comment]
Working on that issue in the branch "frontend-google-scholar"

**Comment by aliramazanmert** [comment]
Implemented this feature on pr #300
