### ISSUE TITLE
Deletion of Not Validated User From Database

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#267]
-If a user is signed up, but after not validated his/her validation code (maybe he/she signed up with unused e-mail address) then this user should be deleted from database. Please implement functions to handle this issue.

**Comment by EnesToptas** [comment]
What do you mean? Maybe they will validate it later. Many websites keep those users for a long time afaik.

**Comment by hazerb** [comment]
Lets think about a scenario that non-person user (machine) tries to signup repeatedly with non-valid e-mails. It never will be validated, and database will be full up with redundant users. Nothing urgent, but maybe timer can be initiated with validation code in future.

**Comment by EnesToptas** [comment]
Yes, this might be implemented in the future. But this is not a bug, however, a design choice and a feature.

**Comment by EnesToptas** [comment]
Implemented in #380.
