### ISSUE TITLE
Check Search Results and Put 'Owner' Mark Near Project Owner 

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#296]
**Issues:** 
1- It seems to me that more related search results occurs back of search result list, check and if this is the issue fix this
2- Put 'owner' mark near project owner when displaying project owner and collaborators
3- Also when a user name is typed and searched, 'all' section of search displays 'no result' although there are users in 'people' section. this result should appear on 'all' section too.

**Comment by cemreefe** [comment]
> 2- Put 'owner' mark near project owner when displaying project owner and collaborators

I addressed and solved this issue on PR #297. It is now waiting for approval.

**Comment by cemreefe** [comment]
> 3- Also when a user name is typed and searched, 'all' section of search displays 'no result' although there are users in 'people' section. this result should appear on 'all' section too.

Fixed with pr #332 

> 1- It seems to me that more related search results occurs back of search result list, check and if this is the issue fix this

This issue was fixed before the milestone presentation.
