### ISSUE TITLE
Fix Recommendation Bug

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#314]
Now at homepage, users own projects are recommended to himself/herself and also he/she is recommended to himself/herself as a user to follow, backend or frontend should fix these issues.

- [x] user recommendations are fixed
- [x] project recommendations are fixed

**Comment by UkcaGreen** [comment]
Self recommending bugs are fixed at this [ pull request ](https://github.com/bounswe/bounswe2020group6/pull/321).
After it is merged I will close this issue.

**Comment by cemreefe** [comment]
> After it is merged I will close this issue.

See pr #321 .
