### ISSUE TITLE
Notification When a User Accepts Collaboration

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#315]
Now, if a user accepts collaboration invitation, the inviter is not getting notified. I think inviter should be notified, please update.
Also when a users request to join a project is accepted requester user should be notified too.

**Comment by aliramazanmert** [comment]
We can't implement that without backend logic

**Comment by aliramazanmert** [comment]
This functionality is implemented and waiting to be merged on pr #405
