### ISSUE TITLE
Frontend Follow and Project View bug

### ISSUE THREAD

**Issue by cihatkapusuz** [bounswe/bounswe2020group6#329]
I looked into [akademise.ml](url) website to check web application's functionality.

There is a bug while following a profile. It shows user's own profile for a second. 
All projects except user's own project is seen private to the user regardless of the privacy of the project.

- [x] Follow bug fix
- [x] Privacy related bug fix

These are some minor bugs I have faced during checking the functionalities of the web application. These must be fixed before the Milestone 2 presentation.

**Comment by cemreefe** [comment]
I have located the bug related to project privacy. I'm working on it.

**Comment by cemreefe** [comment]
I have fixed both bugs on branch frontend-search-fixes. I will close this issue after merging.
