### ISSUE TITLE
Seeing profile from projects Deadline 29.12.2020 23.59

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#336]
We can see projects of users from their profiles but can not see profiles from projects. It is implementation is assigned to @cihatkapusuz .

**Comment by cihatkapusuz** [comment]
User is now able to see profile of the project owner, if s/he came project details from search. Still working on enabling it from the homepage.

**Comment by cihatkapusuz** [comment]
Coming from homepage is left undone this issue will be re-opened after the Milestone 2 presentation.
