### ISSUE TITLE
Prevent Editing Another Users Projects

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#338]
**Problem:** 
Now, its possible that editing another users projects since there is a edit button when i clicked their projects. Edit button should not be seen when i clicked another users project, please fix this.

**Comment by cemreefe** [comment]
I have resolved this issue with [this commit](https://github.com/bounswe/bounswe2020group6/commit/5129cb789463e54062effbc43695e5e877fe47ad).
