### ISSUE TITLE
Edit Project on Frontend status

### ISSUE THREAD

**Issue by cihatkapusuz** [bounswe/bounswe2020group6#341]
** Bug description **

While editing project on frontend if we set the status of the project 'Hibernating', after the editing it shows the status of the project as 'teambuilding'. Also, if we set the status of the project 'Team Building', after the editing it shows the status of the project as 'hibernating'. These should be swapped to be correct.

**How to reproduce it **

Open one of your project details, click edit, set project status as 'Hibernating' or 'Team Building' and save your edit.

**Comment by cemreefe** [comment]
I'm looking into this issue

**Comment by cemreefe** [comment]
See pull request #353

**Comment by cemreefe** [comment]
#353 merged, closing this issue.
