### ISSUE TITLE
Event related pages and components should be created

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#349]
- [x] event details page
- [x] events list component
- [x] event creation page

**Comment by UkcaGreen** [comment]
I am working on event details page.

**Comment by cemreefe** [comment]
I am working on event details page

**Comment by cemreefe** [comment]
I have implemented the event details page (see pr #387 )

**Comment by UkcaGreen** [comment]
I have implemented the event creation page you can check this pull request #385.

**Comment by dogruomerfaruk** [comment]
I have implemented the events list page you can check this pull request #404 .
