### ISSUE TITLE
Requirements Review

### ISSUE THREAD

**Issue by cihatkapusuz** [bounswe/bounswe2020group6#355]
Requirements need to be updated with the changes during the project development.

These are the changes that need to be performed:
- [x] comment related elements should be removed
- [x] rating should replaced with upvote
- [x] remove research area, topic, scope and difficulty from filtering system
- [x] conferences or journal in requirements should replaced with events 
- [x] there should be description for events in glossary

**Comment by UkcaGreen** [comment]
Desired changes applied.
Note: There was an already existing event definition at the glossary part.
