### ISSUE TITLE
Event Functionality

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#362]
Event Functionality will be added to the system by the assignee.
Deadline: 26.01.2021

**Comment by isiktashamza** [comment]
user shall be able to create event
user shall be able to tag their events
user shall be able to add events to their favorite events
user shall be able to see past and future events

**Comment by EnesToptas** [comment]
I have implemented 3 out of 4 in #377 Will implement favorites next

**Comment by EnesToptas** [comment]
I have implemented all of them and merged that branch into backend. Closing this issue.
