### ISSUE TITLE
Implement semantic search

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#365]
Application should have semantic search functionality, please implement it.

**Comment by isiktashamza** [comment]
I created elasticsearch client in my local machine. 
I implemented add, update, delete, search elastic-functions for projects and events. 
With these methods all data about events and projects are saved into elasticsearch dataset, and they are updated regularly in case of any change.
Elasticsearch is like an information retrieval system. The search function of it fetches most related documents based on search query. This way we ensure semantic search.
