### ISSUE TITLE
Frontend Integration of Semantic Search and Tag Filtering

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#373]
Semantic Search and Tag Filtering functionalities should be integrated to frontend after backend implementations are completed.

- [x] Semantic search
- [x] Tag filtering

**Comment by cemreefe** [comment]
I have successfully connected the frontend search page to the new semantic search endpoints. (See p.r. #408 )

**Comment by cemreefe** [comment]
I have successfully implemented tag filtering and tag search functionalities (see p.r. #428 )
