### ISSUE TITLE
Writing User Scenarios

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#38]
Deadline : 29.02.2020 23.59

There will be 3 user scenarios.
1- Profile Page && Comment Part
2- Paper/project idea posting
3- Inviting someone to paper/project

while you are writing, describe clearly:

– The user and their persona (role)
– Preconditions – if any (such as: the user that has already logged in).
– Specific actions to achieve a desired goal (what the user wants to do). Describe each
step until the scenario is completed. Steps must be enumerated.
– Acceptance criteria (the conditions that describe a successful outcome for the action)

Close the issue with a link of the scenarios.

**Comment by isiktashamza** [comment]
there are 3 user scenarios which are guest user, registered user, and company. idea posting and inviting someone are already actions of users and we do not think they are independent scenarios.

**Comment by isiktashamza** [comment]
I and Salih Can Özçelik created User Scenarios
