### ISSUE TITLE
Preparing Presentation Plan and Text

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#380]
In order to present on final milestone presentation, a presentation plan and text must be prepared. 
@UkcaGreen will present the frontend presentation.
@Tubagc will present the mobile presentation.
At least a rehearsal must be done.

Deadline: 25.01.2021 23.55

**Comment by Tubagc** [comment]
We prepared our presentation plans and text.

**Comment by cihatkapusuz** [comment]
Since the presentation is done with the prepared materials, this issue can be closed
