### ISSUE TITLE
Uploaded images don't show up

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#398]
## Description
Newly uploaded profile pictures are unaccesible. They don't load or show up on any place in the web-app.

## Error Message
```
ec2-52-91-31-85.compute-1.amazonaws.com:3000/static/avatars/4ed35470-5e96-11eb-9181-03efa78fa0c3_thispersondoesnotexist0.jpeg:1 GET http://ec2-52-91-31-85.compute-1.amazonaws.com:3000/static/avatars/4ed35470-5e96-11eb-9181-03efa78fa0c3_thispersondoesnotexist0.jpeg net::ERR_CONNECTION_TIMED_OUT
```

## How To Reproduce
1. Login as any user
2. Go to profile
3. Click on profile pic to open upload prompt
4. Select any image and upload
5. Wait for profile picture to load
6. After a while the profile picture will be loaded with a "broken image" placeholder, and the browser console will print the above error message.

**Comment by aliramazanmert** [comment]
This issue is solved by backend, closing
