### ISSUE TITLE
Search bug: some queries yield no results

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#399]
## Description
Some search queries don't yield expected results.

## Error Message
There is no error message. (See below, example result for query "yu" for type 0)
> ![Screenshot from 2021-01-25 03-21-34](https://user-images.githubusercontent.com/44120900/105648456-88fbd480-5ebc-11eb-869e-88e7a07cafd0.png)
This is not the expected behavior since there is a user named "Yuriy Petrov" in the database.

## How To Reproduce
1. Login as any user
2. Enter "y" in the search bar and click search / hit enter
3. You should see that the results include "Yuriy Petrov"
  ![Screenshot from 2021-01-25 03-19-56](https://user-images.githubusercontent.com/44120900/105648494-db3cf580-5ebc-11eb-815a-25a48e4b31c9.png)
4. Now repeat 3 with query "yu".
5. You should see that there are no results for this query.
  ![Screenshot from 2021-01-25 03-20-09](https://user-images.githubusercontent.com/44120900/105648522-045d8600-5ebd-11eb-9f92-e723812ffee9.png)

**Comment by EnesToptas** [comment]
Fixed with the latest PR #407
