### ISSUE TITLE
Projects can't be marked as public OR private

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#401]
## Notice
I'm tagging the frontend member that implemented this page (@cemreefe ) and members from the backend team (@isiktashamza , @EnesToptas ). First, the cause of this bug should be found, and the responsible team should take action.

## Description
A user can not change / update / set a project's privacy.

## Error Message
> No error message

## How To Reproduce
1. Login as any user
2. Click 'Create new project' on profile sider (the sidebar that shows up on the home page)
3. Fill details about an event
4. Click confirm
5. You will be redirected to the Edit project page, where you should see both publicity radio buttons as unchecked.
6. Try to set a publicity option on this page (i.e. choose `Public` or `Private`)
7. Click confirm and you will be redirected to the project details page. Notice how the project 'seems' public no matter the publicity option you chose in the previous step.
8. Click on edit project button to go to the edit project page. Where you can again observe that the radio buttons are unchecked.

**Comment by cihatkapusuz** [comment]
At Android side, project's privacy can be updated. Previously, we were sending integers as privacy but it is changed into booleans at the updated endpoints. That could be the problem for the Frontend side.

**Comment by EnesToptas** [comment]
This should be fixed, after confirmation, we could mark this issue as resolved.

**Comment by aliramazanmert** [comment]
We fixed this issue with a little refactor on frontend as well, closing the issue.
