### ISSUE TITLE
Default biography value displayed as [Object(object)] on edit.

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#402]
## Description
When a user first tries to edit their bio, they see an editable text with value `[Object(object)]`.

## Error Message
> No error message

## How To Reproduce
1. Login as any user with no bio (default bio value)
2. Go to profile page
3. Click edit bio
![Screenshot from 2021-01-25 04-00-29](https://user-images.githubusercontent.com/44120900/105649674-31606780-5ec2-11eb-9d47-5230776a5bbf.png)
![Screenshot from 2021-01-25 04-00-36](https://user-images.githubusercontent.com/44120900/105649675-332a2b00-5ec2-11eb-9ea8-a1c3054174aa.png)

**Comment by cemreefe** [comment]
fixed with [this commit](https://github.com/bounswe/bounswe2020group6/commit/2f1a505bbfb9786964a111efbde18abd8c0377c7).

**Comment by aliramazanmert** [comment]
This issue is resolved, closing.
