### ISSUE TITLE
Taking An Appointment & Meeting With Customer

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#42]
Deadline: 03.03.2020 23.59

- take an appointment
- meet with the customer
- Ask the questions
- take notes
- share them with us.

The person who will ask : Doğukan Kalkan
The person who will take notes : Gülperi Er
And the observer : Emilcan Arıcan

Good luck!

**Comment by gulperii** [comment]
We have met with the customer and we will share the notes after editing.

**Comment by UkcaGreen** [comment]
Meeting notes are shared.
