### ISSUE TITLE
Leading whitespace in the tags

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#432]
There is a leading whitespace in tags that are created at the mobile side. 
There should not be a leading whitespace.

**Comment by cihatkapusuz** [comment]
There was replace operation "Tags:" with empty string in adding tags to the project, but replacement should be "Tags: " with empty string to avoid leading whitespace in tags. I changed that part to fix tag related bug. Updated version is on the android-dev now.
