### ISSUE TITLE
Commented Source Code Android

### ISSUE THREAD

**Issue by cihatkapusuz** [bounswe/bounswe2020group6#436]
Source code must be commented before the final delivery of the source code as wanted in the deliverables.

All members of the mobile team should comment their part in the application.

@cihatkapusuz should comment:

- [x] AddMilestone.java
- [x] AddTag.java
- [x] EditMilestonesActivity.java
- [x] EditProjectActivity.java
- [x] EditTagsActivity.java
- [x] GetProjects.java
- [x] Milestone.java
- [x] Project.java
- [x] ProjectCreationActivity.java
- [x] ProjectCreationActivity2.java
- [x] ProjectDetailsActivity.java
- [x] ProjectDetailsUserActivity.java
- [x] ProjectFiles.java
- [x] ProjectFragment.java
- [x] ProjectInfoEntryFragment.java
- [x] ProjectInfoEntryFragment2.java
- [x] RecyclerViewDetailsAdapter.java
- [x] RecyclerViewFileAdapter.java
- [x] RecyclerViewMilestoneAdapter.java
- [x] RecyclerViewTagAdapter.java
- [x] ShowProjectFilesActivity.java
- [x] Summary.java
- [x] Tag.java

@Tubagc should comment:
- [x] GoogleScholar.java
- [x] GoogleScholarFragment.java
- [x] GoogleScholarPublication.java
- [x] GoogleScholarRVAdapter.java
- [x] Home.java
- [x] HomeFragment.java
- [x] LoginActivity.java
- [x] MainActivity.java
- [x] Notifications.java
- [x] OtherUserProjectsActivity.java
- [x] PopUpAdapter.java
- [x] Profile.java
- [x] ProfileActivity.java
- [x] ProfileFragment.java
- [x] ProfileOthersFragment.java
- [x] Id.java
- [x] RecyclerViewAdapter.java
- [x] Affiliation.java
- [x] Biography.java
- [x] Department.java
- [x] Title.java
- [x] University.java
- [x] Url.java
- [x] RootGetProjects.java
- [x] SearchedUsers.java

@gulperii :
- [x] Collab.java
- [x] Invitation.java
- [x] InvitationActivity.java
- [x] InviteAdapter.java
- [x] RecyclerViewAdapterInvite.java
- [x] Request.java
- [x] RequestAdapter.java
- [x] RequestInvitationActivity.java
- [x] ReceivedInvitationsActivity.java
- [x] SignupActivity.java
- [x] SignupFragment.java
- [x] Follower.java
- [x] FollowingUsers.java
- [x] PersonalInfo.java
- [x] PersonalInfoFragment.java
- [x] ProfileUpdate.java
- [x] ProjectCollaborators.java
- [x] PublicationsFragment.java
- [x] StatsAndOverviewAdapter.java
- [x] StatsAndOverviewFragment.java
- [x] User.java
- [x] UserInterest.java
- [x] Upvote.java
- [x] Token.java

Other team members should comment (they should extect their parts and edit this issue):
- [x] AddEvent.java
- [x] AddEventFragment.java
- [x] AkademiseApi.java
- [x] Event.java
- [x] EventActivity.java
- [x] EventAdapter.java
- [x] EventFilters.java
- [x] EventFragment.java
- [x] EventOperation.java
- [x] MyEventAdapter.java
- [x] MyEventsFragment.java
- [x] UpdateEvent.java
- [x] UpdateEventActivity.java
- [x] UpdateEventFragment.java
- [x] UpdateProject.java
- [x] Validation.java
- [x] ValidationFragment.java

**Comment by cihatkapusuz** [comment]
I finished my part for commenting the source code and pushed the comments into the android-dev.

**Comment by Tubagc** [comment]
I finished commenting the java files that are assigned to me and pushed the commit into the android-dev branch

**Comment by gulperii** [comment]
I finished my part and pushed to the android-dev branch

**Comment by DogukanKalkan** [comment]
I completed the remaining parts.
