### ISSUE TITLE
User Manual for Android Application will be prepared

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#438]
User Manual shall be prepared.
Deadline = 31.01.2021 22.55

@Tubagc should complete these parts of the manual:
- [x] Login Page
- [x] Home Page (Search and Recommendation)
- [x] Navigation Menu
- [x] Notifications
- [x] Profile Page
- [x] Google Scholar

@cihatkapusuz should complete these parts of the manual:
- [x] Project creation
- [x] Project Details (owner perspective, not owner perspective, project files)
- [x] Edit Project (edit milestones, edit tags)

@gulperii should complete these parts of the manual:
- [x] Invitations
- [x] Collaboration Requests and Invite
- [x] Validation Page
- [x] Signup
- [x] Affiliation Entry

The remaining parts shall be completed by @DogukanKalkan 

- [x] Events (Add Event, Fav Event, Update Event)
- [x] Stats and Overviews (Followers and Followings)
- [x] Profile Update (title in the document is Edit Profile) 
- [x] Projects Page (title in the document is Projects Page)
(If there is a functionality that is not listed above, please add it to the list)

**Comment by Tubagc** [comment]
The user manual is prepared [here](https://docs.google.com/document/d/1EDFLIGVGtCb-AuA4_VSqSaEsdHmDHtS8Fg6jp_U-DnI/edit?usp=sharing).

**Comment by Tubagc** [comment]
I prepared my part of the user manual.

**Comment by cihatkapusuz** [comment]
I have completed my part of the user manual.

**Comment by gulperii** [comment]
I have completed my part

**Comment by DogukanKalkan** [comment]
I completed my part.
