### ISSUE TITLE
Communication Plan Fixing

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#44]
Deadline : 03.03.2020 23.59

Communication plan should be fixed according to week 1 feedback. 
The feedback is:

The communication plan should include Github and its related functionalities (such as issue management system) for the communication both within group and with customers. Additionally, one of the main medium for the customer communication is Piazza, which should be also included in the plan. You should be more specific about the meeting locations. BM classes is not good enough, both for your team meeting and customer meeting. Lastly, the purpose of "team meeting" should be widened. What is the real purpose of meeting weekly? Distributing the tasks, or something like that?

**Comment by FarukOzderim** [comment]
Communication plan fixed according to user feedback.
