### ISSUE TITLE
Commenting Source Code

### ISSUE THREAD

**Issue by hazerb** [bounswe/bounswe2020group6#440]
Source code must be commented before the final delivery of the source code as wanted in the deliverables.

All members of the backend team should comment their part in the application.

@isiktashamza   should comment:

- [x] mailController.js
- [x] searchUtil.js
- [x] followRouter.js
- [x] homeRouter.js
- [x] searchRouter.js
- [x] validateRouter.js
- [x] follows.js
- [x] user_ups.js
- [x] elasticUtil.js
- [x] elastic_client.js
- [x] followController.js
- [x] searchController.js

- [x] homeController.js

@hazerb  should comment:
- [x] collabUtil.js
- [x] notificationUtil.js
- [x] postUtil.js
- [x] uploadUtil.js
- [x] collabRouter.js
- [x] fileRouter.js
- [x] postRouter.js
- [x] collab_requests.js
- [x] project_collaborators.js
- [x] project_files.js
- [x] project_milestones.js
- [x] project_tags.js
- [x] projects.js
- [x] collabController.js
- [x] fileController.js
- [x] notificationController.js
- [x] postController.js

@EnesToptas should comment :
- [x] authCheck.js
- [x] cron.js
- [x] email.html
- [x] passwordUtil.js
- [x] userUtil.js
- [x] authRouter.js
- [x] eventRouter.js
- [x] profileRouter.js
- [x] eventFavs.js
- [x] events.js
- [x] users.js
- [x] authController.js
- [x] eventController.js
- [x] profileController.js
- [x] validateController.js

@FarukOzderim  should comment :
- [x] autoCompleteRouter.js
- [x] notificationRouter.js
- [x] db.js
- [x] event_tags.js
- [x] notifications.js
- [x] tags.js
- [x] titles.js
- [x] universities.js
- [x] user_interests.js
- [x] autoCompleteController.js

Apart from those assignments If you see necessity, you can comment other team members code parts too.

**Comment by EnesToptas** [comment]
Do database model tables need to be commented?

**Comment by isiktashamza** [comment]
I commented my part.

**Comment by isiktashamza** [comment]
> Do database model tables need to be commented?

I agree. Database models are self-explanatory. They need not any comment

**Comment by hazerb** [comment]
I commented my part.

**Comment by FarukOzderim** [comment]
Necessary comments are written.
