### ISSUE TITLE
Repo Research Report Fixing

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#45]
Deadline : 03.03.2020 23.59

Repo researches should be fixed according to the feedback of week 1:
"..provide a beneficial information in terms of repository research and the purpose of this assignment."
"..about the status of the repo and how wiki page is used etc."

After you do your job, leave a comment and check the box of your name. Otherwise, it will be labeled as overdue. 

- [x] Salih Can Özçelik
- [x] Hamza Işıktaş
- [x] Gülsüm Tuba Çibuk
- [x] Ezgi Gülperi Er
- [x] Emilcan Arıcan
- [x] Hazer Babür
- [x] Doğukan Kalkan
- [x] Ahmet Berat Can
- [x] Ömer Faruk Özdemir
- [x] Muhammed Enes Toptaş
- [x] Cemre Efe Karakaş

**Comment by salihozcelik** [comment]
I changed the repo research and provide necessary informations.

**Comment by FarukOzderim** [comment]
Edited the repo research according to description.

**Comment by isiktashamza** [comment]
I edited my part by adding some links

**Comment by UkcaGreen** [comment]
I edited my repository research according to description.

**Comment by EnesToptas** [comment]
I did my part.

**Comment by aberatcan** [comment]
I edited my part.

**Comment by Tubagc** [comment]
I edited my part and added some good info about repo itself.

**Comment by DogukanKalkan** [comment]
I edited my part and made some comments about the structure of the repository.

**Comment by gulperii** [comment]
I edited my part

**Comment by hazerbabur2015400078** [comment]
I edited my part.

**Comment by hazerb** [comment]
i edited my part
