### ISSUE TITLE
Completing Requirements Version 1 ( 11)

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#58]
Deadline : 08.03.20 23.59

11 . There should be performance-related and security-related nonfunctional requirements such as hashing, availability of the system, backups etc. Besides, the Android version that is supported, or the browser versions that can be used for your application should be specified.

Related parts of the requirements shall be fixed. 

While fixing the requirements, please check the related parts of [questions](https://github.com/bounswe/bounswe2020group6/wiki/Questions-to-Customer-and-Answers-of-Customer) and [user scenarios](https://github.com/bounswe/bounswe2020group6/wiki/User-Scenarios) .

 Generally, if you think that some requirements are missing, you can add it. It does not have to be related to your part.

**Comment by DogukanKalkan** [comment]
The task is done.
