### ISSUE TITLE
Completing Requirements Version 1 ( Q16, Q17)

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#64]
Deadline : 08.03.20 23.59

Related parts of the requirements shall be fixed/added according to Q16 and Q17.

While fixing the requirements, please check the related parts of [questions](https://github.com/bounswe/bounswe2020group6/wiki/Questions-to-Customer-and-Answers-of-Customer) and [user scenarios](https://github.com/bounswe/bounswe2020group6/wiki/User-Scenarios) .

 Generally, if you think that some requirements are missing, you can add it. It does not have to be related to your part.

**Comment by cemreefe** [comment]
The task is complete.
