### ISSUE TITLE
Creating Use Case Diagrams

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#75]
Assignees will create use case diagrams according to [requirements.](https://github.com/bounswe/bounswe2020group6/wiki/Requirements)
Deadline: _14.03.2020 23.59_

**Comment by FarukOzderim** [comment]
Deadline is extended to 28.03.2020 due to coronavirus break.

**Comment by FarukOzderim** [comment]
Deadline is changed to 21.03.2020 after assingment deadline update.

**Comment by Tubagc** [comment]
I am dividing use cases according to requirements.
1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.7 -> @salihozcelik  (19)
1.1.5, 1.1.6 -> @cemreefe(27) 
1.1.8, 1.1.9, 1.1.10 -> @Tubagc  (22)

**Comment by salihozcelik** [comment]
First draft is completed.
