### ISSUE TITLE
Creating Class Diagram

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#76]
Assignees will create class diagram according to [requirements.](https://github.com/bounswe/bounswe2020group6/wiki/Requirements)
Deadline: _14.03.2020 23.59_

**Comment by FarukOzderim** [comment]
Deadline is extended to 28.03.2020 due to coronavirus break.

**Comment by FarukOzderim** [comment]
Deadline is changed to 21.03.2020 after assingment deadline update.

**Comment by isiktashamza** [comment]
Hamza: User, Comment,Notification,Rate
Berat: Search, Event, Profile,
Doğukan: BaseWork, Invitation, Request, Report

Gülperi: Drawing the diagram.
