### ISSUE TITLE
Creating Sequence Diagrams

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#77]
Assignees will create use case diagrams according to [requirements.](https://github.com/bounswe/bounswe2020group6/wiki/Requirements)
Deadline: _17.03.2020 23.59_

**Comment by FarukOzderim** [comment]
Deadline is extended to 05.04.2020 due to coronavirus break.

**Comment by FarukOzderim** [comment]
Deadline is changed to 24.03.2020 after assingment deadline update.

**Comment by UkcaGreen** [comment]
Sequence diagrams are created according to class diagram, and uploaded to related wiki page.
