### ISSUE TITLE
Asking Questions To Customer

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#78]
Assignee will ask these questions to customer. And share answers with the group.
1-Is filling texts feedback for every mockup or only the 2nd one.  
2-Is there should be a certain path for every mockup or only the 3rd one.  
3-What is the reference in assingment 5 inthis sentence:
(Recall that, each sequence diagram must include a reference identification as well as a clear title and description.)

**Comment by UkcaGreen** [comment]
Asked the questions .
