### ISSUE TITLE
Fixing 3rd user scenarios&mockup according to feedback

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#81]
Lastly, a scenario should focus on a certain path. For example, the last mockups/scenario focuses on more than one thing, like
1-visiting profile page and inspecting the followers
2-Checking the homepage
3-Looking the people who has applied etc.

**Comment by FarukOzderim** [comment]
Deadline _16.03.2020 23.59_

**Comment by Tubagc** [comment]
Action list, scenario, and mockup flow is changed according to the feedback.
only remaining part is mockup figures. More information will be added.
