### ISSUE TITLE
Fixing 2nd user scenarios&mockup according to feedback

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#83]
In the mockups, you need to provide "real data" as much as possible. For example, in google scholar part, or project creation, or about me, or document in the mobile app or... The mockups and the acceptance criteria should be aligned. For example in the second mockup, we cannot see anything about editing the description.

Deadline: _16.03.2020 23.59_

**Comment by cemreefe** [comment]
done
