### ISSUE TITLE
Fixing Requirements According To Feedback

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#85]
You can find the feedback below, you can fix the user requirements and user scenarious corresponding to it for each item. There are a lot of items pls take the initiative and start.
Note that some of these items might have been fixed already, so checkmark the item when you find something like that.

- [x] You can add “conference” or “project” or “paper” to the glossary part.
- [x] 1.1.1 and 1.1.2 — instead of “see” you can write them as “view”
- [x] Cannot I search for users in the system, only papers/projects or events?
- [x] I am confused about the general organization of the requirements. 1.1.1, 1.1.2 and 1.1.3 are independent ones from the rest? Or are they written as “general requirements that can be done by both users” ? What about 1.1.6 and rest?
- [x] 1.1.4.1 “search and see” but “cannot see content”, what can guest user see in the first part? Just the search result?
- [x] 1.1.4.3 — it should be a set of requirements that do not fall under “guests”. 
- [x] 1.1.4.3.1 “users shall be able to register by providing name, surname, unique email address and password”. 
- [x] 1.1.4.3.3 “user shall validate the email address for completing the registration phase”. 
- [x] 1.1.4.3.4 — are there any users who are not academicians? If so, who are they? 
- [x] 1.1.4.3.4 — “users shall provide the information about affiliation”, another requirement as “users shall be able to specify the research interests”… 
- [x] 1.1.4.3.4 — why two photos?
- [x] 1.1.4.3.5 — delete this requirement
- [x] Until 1.1.5, it is “users” but in 1.1.5, it is “user”. You should maintain the consistency throughout the document, which should be “users”.
- [x] 1.1.5.4 — which users? Only project creators can accept or reject the requests. Thus, you can rewrite this as “users as the owner of the projects shall be able to… “.
- [x] 1.1.5.5 — in this requirement, it can be inferred that “users” and “academicians” are separate group of actors of the system. You can write “any user to participate”
- [x] What happens when I invite someone? The receiver side should either accept or reject the invitation, which should be specified in the requirements. 
- [x] 1.1.5.6 — it would be better to provide the functionality of providing or rating during the collaboration, not just after the project completion. 
- [x] I did not understand 1.1.5.7??
- [x] 1.1.5.9 is not in a correct requirements format. Instead, you can rewrite this as “user shall be able to end the looking for collaboration stage to disable the join requests” or something like that. 
- [x] 1.1.5.11 — since we are specifying that “user shall be able to specify a deadline”, instead of “shall specify”, the second part of “make the deadline open” is not necessary. 
- [x] You can delete 1.1.5.13, and rewrite 1.1.5.13.1 as 1.1.5.13. 
- [x] I think 1.1.5.13.2 can be deleted, since it is mostly covered in the previous requirement. 
- [x] 1.1.6.1 — providing affiliation is a must or it is an optional field?
- [x] Besides, you can delete 1.1.6.1.1/2/3 and rewrite 1.1.6.1 as “users shall be able to provide information about the research interests, recent publications and affiliation.”
- [x] 1.1.6.4 — Can I just see? What else? Besides, just invitations, or is there also list of follow requests?
- [x] 1.1.7.1 — instead of “share”, you can express the functionality as “specify” or “provide”. 
- [x] Why 1.1.7.1 is decomposed into several fields, while 1.1.7.2, 1.1.7.3 etc. also include related information? 1.1.7.1.1 until 1.1.7.1.8 should be rewritten. For example, 1.1.7.1 “users shall be able to specify the topic of the research, deadline of submission and milestones.” 1.1.7.2 “users shall be able to share related codes, documents, plots and figures with the collaborators”… 
- [x] Collaborators can add additional files, which should be written. 
- [x] What is the difference between public and private project?
- [x] 1.1.8 should be rewritten from the scratch, like 1.1.7.1. Similar approach can be utilized. For example: 1.1.8.1 “users shall be able to search other users, papers, projects, conferences and journals within the system”. 1.1.8.2: “users shall be able to filter search results with regards to the research area, topic, scope and difficulty”…. 
- [x] What is 1.1.8.4? Where can I see it? Seeing is a requirement?
- [x] What is the difference between 1.1.7 and 1.1.9? They seem similar to me, at least a part of them. 
1.1.9.7 and 1.1.9.8 — what is “seeing in progress?”
- [x] Can I add additional files during the progress status?
- [x] 1.2.1.4 — what is the filtering mechanism for? What are we filtering?
- [x] As 1.2.1.6, the system shall provide a recommendation mechanism for project owners, to recommend possible collaborators based on their research interests, or previous works in that area. 
- [x] 1.2.2.1 — why homepage is provided according to the user’s interest? How does it make a difference?
- [x] 1.2.4.1 — first part is a system req, while second part is a user req. You need to rewrite this. “System shall provide a notification mechanism for informing users about the incoming invitations” etc. 
- [x] Same applies for 1.2.4.3, 1.2.4.4. 
- [x] 1.2.4.5 I assume that this requirement is written by mistake :)) 
- [x] What about the homepage with related to the activity stream? On home page, the users may see the ongoing activities of the collaborators and so on. 
- [x] There should be a “user follow” mechanism in the system, and related set of requirements
  
Non functional reqs in general:
- [x] No GDPR related reqs
- [x] No browser versions that are supported
- [x] No Android versions that are supported
  
General comment about the requirements
Be sure that everything is covered in the requirements document for most of the cases (you may eliminate the edge cases)
Ensure the overall consistency throughout the document. 
Eliminate the redundancy

**Comment by FarukOzderim** [comment]
You may comment how many tasks have you completed after marking them.
Example:
2 of the tasks are complete.

Deadline is 01.04.2020 23:55

**Comment by UkcaGreen** [comment]
7 of the are complete (ones related to 1.1.4.3 and subsections)

**Comment by salihozcelik** [comment]
4 of the tasks are complete.

**Comment by FarukOzderim** [comment]
3 of the tasks are complete.

**Comment by gulperii** [comment]
5 of the tasks are completed.

**Comment by hazerb** [comment]
5 of the tasks are complete

**Comment by EnesToptas** [comment]
7 of the tasks are completed.

**Comment by Tubagc** [comment]
3 of the tasks are completed.

**Comment by DogukanKalkan** [comment]
4 of the tasks are complete.

**Comment by aberatcan** [comment]
2 of the tasks are complete.
