### ISSUE TITLE
Fixing Sequence Diagrams, Feedback For Diagrams

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#86]
- [x] Login /Become academician
We don’t want login as the sequence diagrams, the assignment document says “key use cases”. Login is not a key use case. On the other hand, what is “becoming an academician”? Is it something executed on the system after logging in (no during the registration page)? What is the other user type rather than becoming an academician?
You don’t need to use real data in sequence diagram. It would be enough if you specify “login(username, password)”. 

- [x] Search / Follow
After searching, a list of users should be returned. Then, I can view the profile of a corresponding user among this list. I think I am confused of “getSearchedProfile” and “showProfileSearchResults” messages. 
What is the Boolean Response? What happens if it returns true, or false? What are the alternative scenarios?

- [x] Be private /Reject Invitation
First, I need to go to my profile page or settings. Then I can start the process of making my profile as private. Therefore, there should be initial messages like “viewProfile” or “getProfileInfo” etc. 
Rejecting an invitation is totally independent use case. It should be a separate sequence diagram. But still, why are we rejecting an invitation, which invitation is being rejected?

- [x] Make Comment
It should be redrawn from scratch. All messages are false, since they should represent methods of classes. 
What is the alternative of “if”?
Again, I need to view the profile of the other user in advance, so that I can trigger the commenting operations. Who am I commenting to? Which registered user?
Create messages should be call the of constructor methods. 
Set methods should be implemented, and used as messages as for example setCommentedID(int) 
There should be a check of validity before making comment. I am creating a message object, setting its fields, but the control is made after that?

- [x] File Complaints
Similar to the previous one. 

- [x] Send Collab Request
Similar comments apply here. 

- [x] Create Project
Similar comments

- [x] Delete Account
I would be better not to even draw this diagram :) Please redraw it from scratch. Just 1-2 messages going around...

- [x] Reject Collaboration Invitation
Redraw from scratch.  There is no user searching, then sending invitation, or browsing among the list of invitations, then reject one among the list etc.

**Comment by FarukOzderim** [comment]
Deadline 07.04.2020 23:55
Please mark the fixed items and comment how many of items did you fix.

**Comment by hazerb** [comment]
Fixed 3 of them

**Comment by UkcaGreen** [comment]
Make Comment, File Complaints, and Create Project diagrams are fixed.

**Comment by EnesToptas** [comment]
Fixed 2, removed one of them -Delete Account.
