### ISSUE TITLE
Fixing Use Case Diagrams

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#87]
- [x] Collaborated User will be removed  
- [x] Users will be connected with diagrams  

Deadline: _6.04.2020 23.59_

**Comment by cemreefe** [comment]
I noticed a difficulty in making the connectins. The reason being:
i.e. the use case "view projects" extends with "view private projects", "join projects" etc.
while a non-registered user can view projects, they can't join projects or view private projects. 
so we can't connect user dircetly to view projects, nor can we just connect registered user.

any ideas?

**Comment by salihozcelik** [comment]
Users connected with diagrams.
