### ISSUE TITLE
Server Management Tools Research Flask, Django, Mongo

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#94]
Everyone will research Flash, Django and Mongo, one of these will be selected as server management tool.
Deadline 28.04.2020

- [x] ömer 
- [x] emilcan
- [ ] doğukan
- [ ] cemre
- [x] ahmet
- [x] salih
- [x] tuba
- [ ] hazer
- [ ] ezgi
- [ ] enes
- [ ] hamza

**Comment by Tubagc** [comment]
I found some tutorials for Flask that may help us
1. [Flask Tutorial](https://flask.palletsprojects.com/en/1.1.x/tutorial/) 
2. [Flask Tutorial -Tutorialspoint](https://www.tutorialspoint.com/flask/index.htm)

I think Flask is easier to learn and implement than other ones.

**Comment by Tubagc** [comment]
I found a [tutorial](https://www.tutorialspoint.com/flask/index.htm) that may help us to learn Flask.

**Comment by FarukOzderim** [comment]
Flask is decided as backend tool.
