### ISSUE TITLE
Google scholars API Research

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#97]
Google scholars api and its publicity will be looked up

_Deadline: 07.05.2020 23:55_

**Comment by cemreefe** [comment]
### Google Scholars API
404 Error: no such official API
(see: [this thread on google code](https://code.google.com/archive/p/google-ajax-apis/issues/109))

However there's a third party API I found that can be used
[Github repo of the api with working example](https://github.com/fredrike/googlescholar-api)

**Alternatively** we can use some public APIs:
[A nice collection of public APIs](https://github.com/public-apis/public-apis)
